<?php
// Created: 2024/09/12 13:12:49
// Last modified: 2024/10/16 14:25:14

function departmentSelectComponent($id)
{
    echo `
<select id="` . $id . `" name="account_request[from_dept]" title="From Department" class="form-control">
    <option value="">Current Department</option>
    <option value="Administrative Services">Administrative Services</option>
    <option value="Airport Services">Airport Services</option>
    <option value="Animal Control Officer">Animal Control Officer</option>
    <option value="Animal Services">Animal Services</option>
    <option value="Auditors Office">Auditors Office</option>
    <option value="BCWS Administration">BCWS Administration</option>
    <option value="BCWS Billing">BCWS Billing</option>
    <option value="BCWS Code Enforcement">BCWS Code Enforcement</option>
    <option value="BCWS Engineering">BCWS Engineering</option>
    <option value="BCWS Finance">BCWS Finance</option>
    <option value="BCWS Operations">BCWS Operations</option>
    <option value="BCWS Purchasing">BCWS Purchasing</option>
    <option value="Building & Codes Enforcement">Building & Codes Enforcement</option>
    <option value="Building & Fleet Maintenance">Building & Fleet Maintenance</option>
    <option value="Central FD">Central FD</option>
    <option value="Clerk Of Courts Office">Clerk Of Courts Office</option>
    <option value="Clerk Of Courts Office/DSS">Clerk Of Courts Office/DSS</option>
    <option value="COFC / DSS Incentive">COFC / DSS Incentive</option>
    <option value="Communications">Communications</option>
    <option value="Coroners Office">Coroners Office</option>
    <option value="County Administration">County Administration</option>
    <option value="County Council">County Council</option>
    <option value="County Supervisors Office">County Supervisors Office</option>
    <option value="Cypress Gardens">Cypress Gardens</option>
    <option value="Delinquent Tax">Delinquent Tax</option>
    <option value="DUI Prosecutor Grant">DUI Prosecutor Grant</option>
    <option value="DUI Prosecutor Grant">DUI Prosecutor Grant</option>
    <option value="DUI Prosecutor Grant">DUI Prosecutor Grant</option>
    <option value="Economic Development">Economic Development</option>
    <option value="Emergency Management">Emergency Management</option>
    <option value="Emergency Medical Services">Emergency Medical Services</option>
    <option value="Engineering">Engineering</option>
    <option value="Facilities & Grounds">Facilities & Grounds</option>
    <option value="Farm and Land Services">Farm and Land Services</option>
    <option value="Finance">Finance</option>
    <option value="Fleet Management">Fleet Management</option>
    <option value="Geographic Information Systems">Geographic Information Systems</option>
    <option value="GIS/Address Information">GIS/Address Information</option>
    <option value="GIS/Consortium">GIS/Consortium</option>
    <option value="Grants Administration">Grants Administration</option>
    <option value="Human Resources">Human Resources</option>
    <option value="Human Resources-Services">Human Resources-Services</option>
    <option value="Information Technology">Information Technology</option>
    <option value="JAG Grant - DOM Viol Invest">JAG Grant - DOM Viol Invest</option>
    <option value="JAG Grant - DOM Viol Invest">JAG Grant - DOM Viol Invest</option>
    <option value="JAG Grant - Elder Abuse Invest">JAG Grant - Elder Abuse Invest</option>
    <option value="JAG Grant - Elder Abuse Invest">JAG Grant - Elder Abuse Invest</option>
    <option value="Laboratory">Laboratory</option>
    <option value="Legal">Legal</option>
    <option value="Library Admin">Library Admin</option>
    <option value="Library Admin">Library Admin</option>
    <option value="Library Cane Bay">Library Cane Bay</option>
    <option value="Library Cane Bay">Library Cane Bay</option>
    <option value="Library Daniel Island">Library Daniel Island</option>
    <option value="Library Daniel Island">Library Daniel Island</option>
    <option value="Library Goose Creek">Library Goose Creek</option>
    <option value="Library Goose Creek">Library Goose Creek</option>
    <option value="Library Hanahan">Library Hanahan</option>
    <option value="Library Hanahan">Library Hanahan</option>
    <option value="Library Moncks Corner">Library Moncks Corner</option>
    <option value="Library Moncks Corner">Library Moncks Corner</option>
    <option value="Library Sangaree">Library Sangaree</option>
    <option value="Library Sangaree">Library Sangaree</option>
    <option value="Library St Stephen">Library St Stephen</option>
    <option value="Library St Stephen">Library St Stephen</option>
    <option value="Library State Aid Funds">Library State Aid Funds</option>
    <option value="Magistrate Court">Magistrate Court</option>
    <option value="Magistrate Court/Victim Wit">Magistrate Court/Victim Wit</option>
    <option value="Maintenance Garage">Maintenance Garage</option>
    <option value="Master In Equity">Master In Equity</option>
    <option value="Mosquito Abatement">Mosquito Abatement</option>
    <option value="One Cent Sales Tax">One Cent Sales Tax</option>
    <option value="ONE CENT SALES TAX">ONE CENT SALES TAX</option>
    <option value="Other">Other</option>
    <option value="Permitting">Permitting</option>
    <option value="Planning & Zoning">Planning & Zoning</option>
    <option value="POLL WORKERS ELECTION EXPENSES">POLL WORKERS ELECTION EXPENSES</option>
    <option value="Probate Court">Probate Court</option>
    <option value="Procurement">Procurement</option>
    <option value="Public Defender">Public Defender</option>
    <option value="PUBLIC INFORMATION OFFICE">PUBLIC INFORMATION OFFICE</option>
    <option value="Pump & Plant Electrical Maintenance">Pump & Plant Electrical Maintenance</option>
    <option value="Pump & Plant Mechanical Maintenance">Pump & Plant Mechanical Maintenance</option>
    <option value="RADIO SHOP">RADIO SHOP</option>
    <option value="Real Property Services">Real Property Services</option>
    <option value="Register Of Deeds Office">Register Of Deeds Office</option>
    <option value="Roads & Bridges">Roads & Bridges</option>
    <option value="Safety & Risk Management">Safety & Risk Management</option>
    <option value="Sangaree Special Tax District">Sangaree Special Tax District</option>
    <option value="Scalehouse">Scalehouse</option>
    <option value="Sheriff's Office">Sheriff's Office</option>
    <option value="Sheriff's Office Detention Ctr">Sheriff's Office Detention Ctr</option>
    <option value="Sheriff's Office/School">Sheriff's Office/School</option>
    <option value="Sheriff's Office/Victim Wit">Sheriff's Office/Victim Wit</option>
    <option value="Sheriff-Hwy DUI/EVN">Sheriff-Hwy DUI/EVN</option>
    <option value="Sheriffs Office/DSS">Sheriffs Office/DSS</option>
    <option value="SHF-COPS GRANT">SHF-COPS GRANT</option>
    <option value="SHF-DUI GRANT #2">SHF-DUI GRANT #2</option>
    <option value="SHF-DUI GRANT #2">SHF-DUI GRANT #2</option>
    <option value="SHF-DUI GRANT #2">SHF-DUI GRANT #2</option>
    <option value="Solicitor - JAG Grant">Solicitor - JAG Grant</option>
    <option value="SOLICITOR - STATE">SOLICITOR - STATE</option>
    <option value="Solicitor Grant Juvenile">Solicitor Grant Juvenile</option>
    <option value="Solicitor Grant Violent">Solicitor Grant Violent</option>
    <option value="Solicitor State Grant - Drug Ct">Solicitor State Grant - Drug Ct</option>
    <option value="Solicitor's Office CDV">Solicitor's Office CDV</option>
    <option value="Solicitors Office">Solicitors Office</option>
    <option value="Solicitors Office/PTI Program">Solicitors Office/PTI Program</option>
    <option value="Solicitors Office/Spec Prog">Solicitors Office/Spec Prog</option>
    <option value="Solicitors Office/Victim Wit">Solicitors Office/Victim Wit</option>
    <option value="Solid Waste Collections">Solid Waste Collections</option>
    <option value="Solid Waste Disposal">Solid Waste Disposal</option>
    <option value="Solid Waste Landfill Gas">Solid Waste Landfill Gas</option>
    <option value="Solid Waste Recycling">Solid Waste Recycling</option>
    <option value="SRO ELEM GRANTS">SRO ELEM GRANTS</option>
    <option value="Stormwater Management">Stormwater Management</option>
    <option value="Stormwater Municipalities">Stormwater Municipalities</option>
    <option value="STORMWATER/R&B">STORMWATER/R&B</option>
    <option value="Tax Assessment Review Board">Tax Assessment Review Board</option>
    <option value="Tourism">Tourism</option>
    <option value="TRAFFIC GRANT - SHERIFF">TRAFFIC GRANT - SHERIFF</option>
    <option value="Treasurers Office">Treasurers Office</option>
    <option value="Treatment Plant">Treatment Plant</option>
    <option value="Veterans Affairs">Veterans Affairs</option>
    <option value="VICTIM ADVOCATE GRANT">VICTIM ADVOCATE GRANT</option>
    <option value="VICTIM ADVOCATE GRANT">VICTIM ADVOCATE GRANT</option>
    <option value="VICTIM ADVOCATE GRANT">VICTIM ADVOCATE GRANT</option>
    <option value="Voters Registration & Elections">Voters Registration & Elections</option>
    <option value="Wastewater Collections">Wastewater Collections</option>
    <option value="WASTEWATER COLLECTIONS">WASTEWATER COLLECTIONS</option>
    <option value="Water Distribution">Water Distribution</option>
    <option value="Whitesville FD">Whitesville FD</option>
</select>`;
}
