INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('ADKINS LNDG - MEGA BOAT LNDG', 1059);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('ADMIN ANNEX', 1040);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('AIRPORT CORPORATE HANGAR', 1120);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('AIRPORT HANGAR', 1123);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('AIRPORT MAINTENANCE HANGAR', 1121);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('AIRPORT SHADE HANGAR', 1122);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('AIRPORT TERMINAL', 1003);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('AIRPORT TRACTOR SHED', 1124);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('ALVIN COMMUNITY CENTER', 1004);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('BERKELEY COUNTY ADMINISTRATION BUILDING', 1005);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('BERKELEY COUNTY ANIMAL CENTER', 1099);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('BERKELEY COUNTY ANIMAL CENTER STORAGE BLDG', 1094);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CAINHOY COMMUNICATION TOWER', 1008);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CAINHOY COMMUNITY CENTER', 1009);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CHAMBER OF COMMERCE - NESBITT HOUSE', 1068);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('COM BUILDING IN SANDRIDGE', 1012);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('COMM TOWER AT LANDFILL', 1016);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('COMM TOWER ON HWY 41', 1017);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('COMM TOWER ON HWY 52 - WALMART', 1018);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('COMMUNICATION BUILDING-HWY 403', 1019);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('COMMUNICATION BUILDING-HWY 45', 1020);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CORONERS OFFICE - GULLEDGE ST', 1129);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('COURTHOUSE ANNEX', 1021);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - AQUARIUM', 1100);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - BIRD HOUSE', 1106);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - BOAT DOCK', 1112);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - BOAT DOCK PORTABLE SHED', 1113);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - BUTTERFLY HOUSE', 1105);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - CONFERENCE COTTAGE', 1101);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - DEAN HALL', 1102);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - GIFT SHOP/PORTABLE STORAGE', 1109);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - HERITAGE ROOM', 1110);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - MAINTENANCE BREAK ROOM', 1117);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - MAINTENANCE SHOP BLDG', 1108);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - MENS RESTROOMS', 1114);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - OFFICE BUILDING', 1103);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - OUTSIDE STAGE', 1116);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - PICNIC SHELTERS', 1111);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - TICKET BOOTH', 1107);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - VISITORS CENTER/GIFT SHOP', 1104);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS - WOMENS RESTROOMS', 1115);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('CYPRESS GARDENS BOAT LANDING', 0009);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('DETENTION CENTER (HILL FINKLEA)', 1024);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('DETENTION CENTER STORAGE BUILDING', 1118);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS ADMINISTRATION BUILDING', 1027);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS LOGISTICS - BUILDING C', 0008);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS MEDIC 10-STATE RD-176 SVILLE-LEBANON', 1037);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS MEDIC 1-GOOSE CREEK', 1028);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS MEDIC 2-BLDG-SUMMERVILLE', 1029);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS MEDIC 3-MONCKS CORNER', 1030);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS MEDIC 4-CROSS RENTAL BLDG', 1031);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS MEDIC 5-ST STEPHEN', 1032);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS MEDIC 6-JAMESTOWN', 1033);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS MEDIC 7-CAINHOY', 1034);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS MEDIC 8-DANIEL ISLAND', 1035);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS MEDIC 9-PINERIDGE FD', 1036);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EMS MEDIC 13-CANE BAY FD', 0007);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('EVIDENCE/FORENSICS BLDG', 1039);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('FACILITIES AND GROUNDS', 1038);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('FLEET MAINTENANCE GARAGE', 1119);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('GOOSE CREEK - HEALTH DEPARTMENT', 1045);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('GOOSE CREEK SERVICE CENTER', 1041);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('GUARD HOUSE - SECURITY GATE', 1042);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('GUARDIAN AD LITEM', 1043);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('HEALTH DEPT-CROSS', 1044);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('HEALTH DEPT-ST STEPHEN', 1046);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('HISTORICAL COURTHOUSE', 1069);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('JAIL STORAGE BLDG', 1049);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('JUSTICE AND PUBLIC SAFETY CENTER', 1051);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('LIBRARY - CANE BAY', 1127);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('LIBRARY - MONCKS CORNER', 1052);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('LIBRARY ADMIN OFFICES', 1056);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('LIBRARY/MAGISTRATES - ST STEPHEN', 1057);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('LIBRARY-DANIEL ISLAND', 1053);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('LIBRARY-GOOSE CREEK', 1054);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('LIBRARY-HANAHAN', 1055);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('LIBRARY-SANGAREE', 1058);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('MAGISTRATE OFFICE-GOOSE CREEK', 1061);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('MAGISTRATE OFFICE-JAMESTOWN', 1062);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('MAUDE CALLEN BUILDING - DSS, VOTERS, RECORDS ADMIN SVCS', 1026);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('MC - HEALTH DEPT (OLD HOSPITAL)', 1070);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('MORGUE', 1065);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('MOSQUITO ABATEMENT', 1125);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('MOSQUITO ABATEMENT STORAGE', 1126);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('NARCOTICS TRAILER OFFICE', 1067);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('PAINT SHOP', 1072);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('PINEVILLE REC CENTER', 1076);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('PUBLIC DEFENDER', 1025);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('QUENBY BOAT LANDING', 1079);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('RADIO SHOP', 0006);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('RECORDS RETENTION TRAILER', 1081);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('RECORDS STORAGE BUILDING', 1080);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('ROADS AND BRIDGES', 1078);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('SANGAREE SPECIAL TAX DISTRICT (MAINTENANCE SHOP)', 1086);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('SENIOR CITIZENS-GOOSE CREEK', 1088);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('SENIOR CITIZENS-MONCKS CORNER', 1089);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('SENIOR CITIZENS-PINEVILLE', 1090);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('SENIOR CITIZENS-ST STEPHEN', 1091);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('SHERIFFS ANNEX/RESCUE BLDG', 1083);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('SHERIFFS SUB STATION-SANGAREE', 1092);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('SPIERS LANDING', 1095);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('TRAINING CENTER', 1096);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('WATER AND SANITATION', 1098);
INSERT INTO data_facilities_locations (sName, iLegacyId) VALUES('WATER AND SANITATION', 1099);