INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('ST STEPHEN MAGISTRATE',33008);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF Administration' ,34001);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF R & B Capital Impr Purch' .,34002);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF EMS Capital Improv. Purch' .,34003);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF-Sheriff' ,34010);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF-Facilities and Grounds' ,34012);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF-Information Technology' ,34013);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF Library' ,34016);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF Solicitor' ,34017);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF Building and Codes' ,34018);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF Mosquito Abatement' ,34019);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF Maintenance Garage' ,34023);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF Supervisor' ,34032);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF Coroner' ,34036);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF EPD' ,34037);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF Communications' ,34038);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Courthouse Improvements' ,34043);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF Radio Shop' ,34045);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CIF Animal Control' ,34046);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('2014 One Cent Admin' ,36001);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('County Council' ,41101);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('County Delegation' ,41102);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Probate Judge' ,41201);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Master-in-Equity' ,41202);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Solicitor',41203);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Solicitor PTI' ,41204);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Magistrates',41206);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Public Defender' ,41207);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Solicitor State Funds' ,41208);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Clerk of Court DSS' ,41209);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Clerk of Court',41210);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Clerk of Court DSS Incentive',41212);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Solicitor Expungements',41218);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('County Supervisor',41301);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Registration & Elections',41401);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Board of Voter Registration',41402);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Election Expenses (Pollwks'),41403);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Election Exp Municipalities',41404);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Human Resources',41501);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Legal',41502);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Public Information Officer',41503);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Finance Department',41504);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Treasurer',41505);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Auditor',41506);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Real Property Services',41507);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Tax Collector',41508);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Forfeited Land Commission',41509);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Register of Deeds',41510);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Planning and Zoning',41512);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Procurement',41513);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Administrative Services',41514);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Information & Technology Serv',41515);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Fleet Operations',41516);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Building and Code Enforcement',41517);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Permitting',41518);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Board of Assessment Appeals',41519);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Risk Management',41520);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Non Departmental Expenses',41521);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Print Shop',41523);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Sheriff',42101);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Coroner',42102);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Communications',42103);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Sheriff DSS',42104);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('School Resource Off-School Fds',42109);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Emergency Prepared-Misc Grants',42140);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('1V18042 Victim Advocate',42176);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BC Traffic Unit PT2020HS1920 ',42183);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('M4CS2020HS5320 DUI Pros',42184);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('M4HVE2020HS4720 DUI Capacity',42185);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('SRO Berkeley Academy',42194);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Shared Portion Fire Fees',42204);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Radio Shop',42210);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Alvin Fire',42220);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Bonneau Fire',42223);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('C&B Fire',42225);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Cainhoy Fire',42229);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Caromi Village Fire',42231);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Cordesville Fire',42233);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Cross Fire',42235);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Eadytown Fire',42240);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Forty-One Fire',42245);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Goose Creek Fire',42248);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Huger Fire',42250);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Jamestown Fire',42255);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Lake Moultrie Fire',42260);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Lebanon Fire',42265);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Longridge Fire',42268);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Macedonia Fire',42270);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Moncks Corner Fire',42275);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Pimlico Fire',42280);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Pine Ridge Fire',42283);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Pineville Fire',42286);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Pringletown Fire',42288);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('St Stephen Fire',42290);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Sandridge Fire',42292);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Santee Circle Fire',42295);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Shulerville\Honey Hill',42296);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Whitesville Fire',42298);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Detention Center',42301);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('E911 Emergency Telephone',42501);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('E911 State Reimbursement',42502);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Maintenance Garage',43101);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Roads & Bridges',43103);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Engineering',43104);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Economic Development Local Fds',43107);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Storm Water Management Program',43111);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Storm Water Roads and Bridge',43115);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('County - Storm Water Capital',43120);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Goose Creek-Storm Water Capita',43121);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Hanahan-Storm Water Capital',43122);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('St Stephen-Storm Water Capital',43123);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Health State',44101);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Animal Center',44102);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Mosquito Abatement',44103);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Emergency Medical Services',44104);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Veterans Services',44105);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Animal Control Officer',44112);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Municipal EMS Contracts',44114);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('EMS Billing',44115);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Social Services',44401);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Mental Health',44402);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Berkeley Citizens',44403);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Farm and Land Services',44405);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Medically Indigent',44406);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Senior Citizens',44407);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Victims Witness Advocate',44416);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Victim Witness-Solicitor',44417);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Victim Witness-Magistrate',44418);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Victim Witness-Sheriff',44419);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Cypress Gardens',45201);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Library - State Aid',45507);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Library - E Rate',45516);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Library',45519);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Library-Moncks Corner',45520);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Library-Goose Creek',45521);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Library-Hanahan',45522);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Library-Sangaree',45523);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Library-St. Stephen',45524);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Library-Daniel Island',45525);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Library - Cane Bay',45526);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Debt Service',46001);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Airport Operations',47001);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Facilities & Grounds',47002);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('HR Services Department',47003);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Crime Stoppers',47004);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Santee Cooper Country',47005);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Regional Development Alliance ',47006);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCD Council of Governments',47007);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Contingency Fund',47010);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Geographic Information System',47013);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('State Accommodations Tax',47014);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('County Accommodations Fee',47015);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Sangaree Special Tax District',47018);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('GIS-Non consortium expenses',47032);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Trident Tech Nursing Bldg',47034);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CDBG 2022 Grant Admin',47038);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('CDBG 2022 Grant Project',47039);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('AIP Impr Misc Grants',47045);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Airport Easement 2021',47065);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Airport Obstruction Removal',47066);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Devon Forest Special Tx Dist',47080);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Pimlico Special Tax District',47084);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Tall Pines Special Tx District',47088);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Tourism',47090);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Tourism Grants',47093);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Fleet Administration',47213);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('Emergency Preparedness',47214);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Executive',48011);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Human Resources',48012);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS DCIT',48013);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Finance',48014);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Engineering',48015);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Billing',48016);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Safety',48017);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Purchasing',48018);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Laboratory',48019);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Operations',48020);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Wastewater Collections',48023);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Water Distribution',48025);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Lower Treatment Plant',48030);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS PPM Mechanical',48032);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS PPM Electrical',48033);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Bldg and Fleet Maint',48034);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Solid Waste Recycling',48041);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Solid Waste Disposal',48042);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Solid Waste Collections',48043);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) values('BCWS Scalehouse',48044);
INSERT INTO data_departments (sDepartmentName, iDepartmentNumber) VALUES ('BCWS Solid Waste Landfill Gas',48045);
