insert into data_event_locations (iLocationId, sLocationName) values (4,'Assembly Room');
insert into data_event_locations (iLocationId, sLocationName) values (23,'BCWS Engineering Conference Room');
insert into data_event_locations (iLocationId, sLocationName) values (28,'BCWS Executive Conference Room');
insert into data_event_locations (iLocationId, sLocationName) values (24,'BCWS Operations Bay Area');
insert into data_event_locations (iLocationId, sLocationName) values (25,'BCWS Solid Waste Bay Area');
insert into data_event_locations (iLocationId, sLocationName) values (27,'BCWS Training Room');
insert into data_event_locations (iLocationId, sLocationName) values (29,'BCWS Treatment Plant Breakroom/Shed Area');
insert into data_event_locations (iLocationId, sLocationName) values (6,'Councils Conference Room (Room 100)');
insert into data_event_locations (iLocationId, sLocationName) values (5,'Councils Conference Room (Room 125)');
insert into data_event_locations (iLocationId, sLocationName) values (22,'Courthouse - Courtroom A');
insert into data_event_locations (iLocationId, sLocationName) values (18,'Courthouse - Courtroom E');
insert into data_event_locations (iLocationId, sLocationName) values (16,'Courthouse - Grand Jury Room');
insert into data_event_locations (iLocationId, sLocationName) values (10,'Courthouse - Jury Panel Room');
insert into data_event_locations (iLocationId, sLocationName) values (17,'Courthouse - Jury Room B');
insert into data_event_locations (iLocationId, sLocationName) values (13,'Dean Hall - Cypress Gardens');
insert into data_event_locations (iLocationId, sLocationName) values (20,'Emergency Services Training Center');
insert into data_event_locations (iLocationId, sLocationName) values (34,'EOC - EMD Training - Admin Bldg');
insert into data_event_locations (iLocationId, sLocationName) values (31,'Fleet Management Directors Office');
insert into data_event_locations (iLocationId, sLocationName) values (9,'Goose Creek Satellite Office');
insert into data_event_locations (iLocationId, sLocationName) values (36,'Heritage Room - Cypress Gardens');
insert into data_event_locations (iLocationId, sLocationName) values (8,'Human Resources Department');
insert into data_event_locations (iLocationId, sLocationName) values (33,'IT Multi Function Room');
insert into data_event_locations (iLocationId, sLocationName) values (19,'Live Oak Complex - Magistrate Courtroom A');
insert into data_event_locations (iLocationId, sLocationName) values (14,'Live Oak Complex - Magistrate Courtroom B');
insert into data_event_locations (iLocationId, sLocationName) values (15,'Live Oak Complex - Magistrate Courtroom C');
insert into data_event_locations (iLocationId, sLocationName) values (11,'Live Oak Complex - Other');
insert into data_event_locations (iLocationId, sLocationName) values (1,'Multi-Purpose Room - Room 106B');
insert into data_event_locations (iLocationId, sLocationName) values (37,'SO Annex');
insert into data_event_locations (iLocationId, sLocationName) values (32,'Supervisors Conference Room');
insert into data_event_locations (iLocationId, sLocationName) values (35,'Wellness Clinic');