INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('911 Communications','911 Communications','843-719-4169');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('911 Communications Emergency Medical Dispatcher','911 Communications','843-719-4169');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('911 Communications Emergency Medical Dispatcher','911 Communications','843-719-4170');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('911 Communications Fax','911 Communications','843-719-4165');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Administrative Services Mailroom','Administrative Services','843-719-4105');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Administrative Services Mailroom Fax','Administrative Services','843-719-4111');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Administrative Services Records','Administrative Services','843-719-4148');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Airport','Airport','843-899-7711');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Airport Fax','Airport','843-719-4752');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Airport Line #1','Airport','843-719-4751');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Alcohol and Drug Commission','Alcohol and Drug Commission','843-761-8272');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Animal Control Fax','Animal Control','843-719-4053');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Animal Shelter','Animal Center','843-719-5050');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Auditor','Auditor','843-719-4309');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Auditor #1','Auditor','843-719-4036');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Auditor #2','Auditor','843-719-4033');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Auditor Fax','Auditor','843-719-4128');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Backyard Burning','Backyard Burning','800-895-7063');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Beer and Liq. License','Beer and Liq. License','803-898-5864');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley Citizens Chas. Line','Berkeley Citizens','843-853-9075');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley Citizens Moncks Corner','Berkeley Citizens','843-761-0300');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley County Charleston Line','Administrative Services','843-723-3800');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley County Forestry Comm','Forestry Department','843-719-4352');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley County Moncks Corner','Administrative Services','843-761-6900');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley County School District','Berkeley County School District','843-899-8600');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley County School District Adult Education','Berkeley County School District','843-899-8690');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley County School District Chas. Line','Berkeley County School District','843-723-4627');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley County School District St. Stephen Line','Berkeley County School District','843-567-3141');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley County St. Stephen','Administrative Services','843-567-3136');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley Electric Coop','Berkeley Electric Coop','843-761-8200');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley Electric Coop Chas. Line','Berkeley Electric Coop','843-553-5020');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley Independent Fax','Public Information Office','843-899-6996');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley Independent Moncks Corner','Public Information Office','843-761-6397');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Berkeley Industries Moncks Corner','Berkeley Industries','843-761-0306');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Better Business Bureau','Better Business Bureau','843-766-9616');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Bonneau Town Hall','Town of Bonneau','843-825-3385');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Building and Codes Enforcement','Building and Codes Enforcement','843-719-4758');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Building and Codes Enforcement Fax','Building and Codes Enforcement','843-719-4053');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Building and Codes Enforcement Goose Creek','Building and Codes Enforcement','843-824-2200');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Business Name Registry','Business Name Registry','803-734-2159');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Callen Lacey','Callen Lacey','843-761-5360');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Cane Bay Library','Libraries','843-719-4796');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Census Bureau Toll Free','Census Bureau Toll Free','888-722-8995');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Chamber of Commerce Moncks Corner','Moncks Corner Chamber of Commerce','843-761-8238');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Adminstrator','Charleston County','843-958-4000');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Assessments and Mapping','Charleston County','843-958-4180');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Assessor','Charleston County','843-958-4100');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Auditor','Charleston County','843-958-4200');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Board Of Assessment','Charleston County','843-958-4190');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Budget','Charleston County','843-958-4640');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Business License','Charleston County','843-958-4880');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Capital Projects','Charleston County','843-724-6750');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Clerk Of Court','Charleston County','843-724-3729');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Community Service','Charleston County','843-958-4500');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Controller','Charleston County','843-958-4600');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County County Council','Charleston County','843-958-4030');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Data Processing','Charleston County','843-958-4900');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Delinquent Tax','Charleston County','843-958-4570');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County DSS','Charleston County','843-953-9402');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Economic Development','Charleston County','843-958-4500');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Family Court','Charleston County','843-958-4400');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Grants','Charleston County','843-958-4520');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Internal Auditor','Charleston County','843-958-4290');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Jail','Charleston County','843-529-7300');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Legal','Charleston County','843-958-4010');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Legislative Delegation','Charleston County','843-720-7080');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Mailroom','Charleston County','843-958-4680');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Operation','Charleston County','843-958-4060');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Personnel','Charleston County','843-958-4700');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Procurement','Charleston County','843-958-4750');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Risk Management','Charleston County','843-958-4270');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County RMC','Charleston County','843-958-4800');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Security','Charleston County','843-958-4660');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Support','Charleston County','843-958-4040');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Charleston County Treasurer','Charleston County','843-958-4360');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Children and Family Services','Children and Family Services','843-577-0772');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('City of Charleston City Hall','City of Charleston','843-577-6970');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clemson Extension','Clemson Extension','843-719-4140');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clemson Extension Activity Rm','Clemson Extension','843-719-4141');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clemson Extension Fax','Clemson Extension','843-761-4221');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clerk Of Court Bailiff Courthouse Annex','Clerk Of Court','843-719-4457');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clerk Of Court C/Plea and G/Sess Fax','Clerk Of Court','843-719-4509');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clerk Of Court Courtroom E Bailiff','Clerk Of Court','843-719-4468');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clerk Of Court Family Court (P.O. Box 219)','Clerk Of Court','843-719-4500');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clerk Of Court Family Court DA Window','Clerk Of Court','843-719-4492');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clerk Of Court Family Court Fax','Clerk Of Court','843-719-4509');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clerk Of Court Family Court Front Window','Clerk Of Court','843-719-4501');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clerk Of Court Jury Panel Room','Clerk Of Court','843-719-4456');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clerk Of Court Jury Room A','Clerk Of Court','843-719-4480');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clerk Of Court P.O. Box 219','Clerk Of Court','843-719-4400');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clerk Of Court Premliminary Hearings','Clerk Of Court','843-719-4535');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Clerk Of Court Summary Court','Clerk Of Court','843-719-4050');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Consumer Affairs','Consumer Affairs','800-922-1594');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Contractor License','Contractor License','803-896-4686');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Coroner','Coroner','843-719-4566');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Coroner Fax','Coroner','843-719-4570');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Council Of Governments','Council Of Governments','843-529-0400');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('County Council','County Council','843-719-4092');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('County Council Assembly Room','County Council','843-719-4020');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('County Council Fax','County Council','843-719-4158');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('County Supervisors Office','County Supervisors Office','843-719-4094');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('County Supervisors Office Conference Room','County Supervisors Office','843-719-4161');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('County Supervisors Office Fax','County Supervisors Office','843-719-4381');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Credit Bureau','Credit Bureau','800-944-1122');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Credit Union','Credit Union','843-761-8298');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Cypress Gardens','Cypress Gardens','843-553-0515');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Cypress Gardens #2','Cypress Gardens','843-553-1167');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Cypress Gardens Fax','Cypress Gardens','843-569-0644');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Delinquent Tax Collector','Delinquent Tax Collector','843-719-4030');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Delinquent Tax Collector Fax','Delinquent Tax Collector','843-719-4842');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dept. Of Revenue Tax Charts','Dept. Of Revenue Tax Charts','843-852-3600');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center 300 California Ave','Detention Center','843-719-4341');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Bookings','Detention Center','843-719-4341');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Clinic','Detention Center','843-719-4551');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Clinic','Detention Center','843-719-4233');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Control Room','Detention Center','843-719-4554');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Fax','Detention Center','843-719-4592');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Guard Front Desk','Detention Center','843-719-4919');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Guard Front Desk','Detention Center','843-719-4918');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Guard/Security Officer Front Desk – Cell','Detention Center','843-297-1040');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Hill-Finklea','Detention Center','843-719-4390');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Kitchen','Detention Center','843-719-4550');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Magistrate','Detention Center','843-719-4349');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Records','Detention Center','843-719-4557');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Sheriff Book','Detention Center','843-719-4546');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Detention Center Victim Advocate','Detention Center','843-719-4296');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('DHEC Environmental Control','DHEC','843-953-0150');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('DIG','Palmetto Utility Protection Services','(888) 721-7877');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('DMV Mount Pleasant','DMV','843-884-9760');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('DMV Ladson','DMV','843-572-7854');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('DMV Moncks Corner #1','DMV','843-761-3686');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('DMV Moncks Corner #2','DMV','843-761-3686');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Administrative Services','Dorchester County','843-832-0112');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Animal Control','Dorchester County','843-832-0015');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Assessor','Dorchester County','843-832-0162');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Auditor','Dorchester County','843-832-0118');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Central Traffic Cour','Dorchester County','843-875-2380');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Clemson Extension','Dorchester County','843-832-0135');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Clerk Of Court','Dorchester County','843-832-0160');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County County Council','Dorchester County','843-832-0196');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Election Commission','Dorchester County','843-832-0132');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Emerg. Preparedness','Dorchester County','843-832-0343');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Finance','Dorchester County','843-832-0134');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Jail','Dorchester County','843-563-3511');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Magistrate','Dorchester County','843-832-0370');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Planning','Dorchester County','843-832-0020');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Probate Court','Dorchester County','843-832-0105');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Public Works','Dorchester County','843-832-0700');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Purchasing','Dorchester County','843-832-0134');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Rmc','Dorchester County','843-832-0182');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Roads And Bridges','Dorchester County','843-832-0070');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Sheriff','Dorchester County','843-563-3511');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Tax Collector','Dorchester County','843-832-0110');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Treasurer','Dorchester County','843-832-0115');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Veterans Affairs','Dorchester County','843-821-0116');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Voter Registration','Dorchester County','843-821-0132');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Dorchester County Water and Sanitation','Dorchester County','843-821-9524');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('E-911 Street Addressing','Address Information','843-719-4113');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Economic Development','Economic Development','843-719-4175');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Economic Development Berk/Dorch','Economic Development','843-761-6936');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Economic Development Berk/Dorch | Chas. Line','Economic Development','843-723-9285');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Economic Development Berk/Dorch | St. Stephen Line','Economic Development','843-825-3679');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Economic Development Fax','Economic Development','843-719-4381');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Elderlink Incorporated','Senior Citizens','843-554-2275');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Management','Emergency Management','843-719-4166');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Management Fax','Emergency Management','843-719-4353');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services','Emergency Medical Services','843-719-4180');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services Dispatch Supervisor','Emergency Medical Services','843-719-4185');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services Fax','Emergency Medical Services','843-719-4827');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services Medic 1 (Goose Creek)','Emergency Medical Services','843-764-4600');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services Medic 2 (Summerville)','Emergency Medical Services','843-871-1519');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services Medic 4  (Cross)','Emergency Medical Services','843-719-4221');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services Medic 5 (St. Stephen)','Emergency Medical Services','843-567-7367');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services Medic 6  (Jamestown)','Emergency Medical Services','843-719-4222');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services Medic 7 (Cainhoy)','Emergency Medical Services','843-719-4768');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services Medic 8 (Daniel Island)','Emergency Medical Services','843-849-1523');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services Medic Echo 1','Emergency Medical Services','843-849-1523');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services Shift Supv','Emergency Medical Services','843-719-4115');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Emergency Medical Services Training Center','Emergency Medical Services','843-719-4350');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Engineering','Engineering','843-719-4127');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Facilities And Grounds','Facilities and Grounds','843-719-4135');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Facilities and Grounds Custodian/Supervisor','Facilities and Grounds','843-719-4927');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Facilities And Grounds Emergency Pager','Facilities and Grounds','(888) 667-0903');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Facilities And Grounds Fax','Facilities and Grounds','843-719-4703');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Facilities And Grounds Guard Shack Main Complex','Facilities and Grounds','843-719-4152');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Family Planning','Family Planning','843-719-4319');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fedex','Administrative Services','800-463-3339');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('FEMA','FEMA','800-621-3362');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fennel Container','Tree Trimming -Town','800-521-1797');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('FHA','FHA','843-727-4160');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('FHA Mall Drive','FHA','843-727-4327');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Finance','Finance','843-719-4162');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Finance Fax','Finance','843-719-4107');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Alvin Rural','Fire Department','843-567-4899');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Bonneau','Fire Department','843-825-3385');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Bonneau Rural','Fire Department','843-825-6628');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department C&B Rural','Fire Department','843-873-0714');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Cainhoy Rural','Fire Department','843-881-2941');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Caromi Rural','Fire Department','843-553-3040');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Cordesville Rural','Fire Department','843-899-4644');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Cross Rural','Fire Department','843-753-2111');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Daniel Island','Fire Department','843-216-3264');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Eadytown Rural','Fire Department','843-351-4712');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Forty One Rural','Fire Department','843-825-3357');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Girl Scout Plantatio Moncks Corner','Fire Department','843-336-3251');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Goose Creek Rural','Fire Department','843-797-3112');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Goose Creek Rural 2','Fire Department','843-553-3018');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Huger Rural','Fire Department','843-336-4511');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Jamestown Rural','Fire Department','843-257-4600');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Lake Moultrie Rural','Fire Department','843-825-6628');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Lake Ridge Rural','Fire Department','843-688-5199');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Lebanon Rural','Fire Department','843-688-5519');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Macedonia Rural','Fire Department','843-565-3809');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Macedonia Rural2','Fire Department','843-336-3998');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department MC Rural','Fire Department','843-899-2259');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department MC Rural 2','Fire Department','843-899-7211');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Moncks Corner','Fire Department','843-719-7990');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Pimlico Rural','Fire Department','843-761-3232');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Pineville/Russellville','Fire Department','843-567-2768');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Prdge Ru 22','Fire Department','843-821-6727');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Pringletown Rural','Fire Department','843-688-5111');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Sandridge Fire Department','Fire Department','843-688-4344');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Santee Circle Rural','Fire Department','843-761-3953');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Shularvill |Sand Hill','Fire Department','843-257-2055');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department St. Stephen Rural','Fire Department','843-567-2768');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Whitesville Rural','Fire Department','843-761-1628');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Department Whiteville Rural 2','Fire Department','843-761-1729');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fire Marshall','Fire Marshall','843-719-4291');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Forestry Department','Forestry Department','843-899-2221');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Forestry Department Bonneau','Forestry Department','843-825-3326');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Forestry Department Ranger Moncks Corner','Forestry Department','843-899-2221');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Forestry Department Ranger Toll Free','Forestry Department','800-763-3824');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Fraudulent Checks','Fraudulent Checks','843-719-4594');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Geographic Information Systems','Geographic Information Systems','843-719-4049');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Geographic Information Systems Fax','Geographic Information Systems','843-719-4190');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Goose Creek City Hall','Goose Creek City Hall','843-797-6220');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Goose Creek Gazette Fax','Goose Creek Gazette','843-572-0312');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Goose Creek Police','Goose Creek Police','843-863-5200');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Government Loans','Government Loans','843-529-0400');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Guardian Ad Litem (109 N. Live Oak Dr.)','Guardian Ad Litem (109 N. Live Oak Dr.)','843-719-4953');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Habitat For Humanity','Habitat For Humanity','843-761-8989');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Hanahan City Hall','Hanahan City Hall','843-554-4221');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Hanahan News Fax','Hanahan News','843-744-5505');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Headstart Program Rev. Myers','Headstart Program Rev. Myers','843-719-7200');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department 109 W. Main St','Health Department','843-719-4600');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Custodian','Health Department','843-719-4694');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Dorchester County','Health Department','843-832-0107');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Envir. Health','Health Department','843-953-0150');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Family Planning','Health Department','843-719-4679');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Family Planning','Health Department','843-719-4680');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Fax','Health Department','843-719-4656');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Goose Creek','Health Department','843-572-3313');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Health Education','Health Department','843-719-4606');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Immunization Clerk','Health Department','843-719-4687');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Immunization Room','Health Department','843-719-4684');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Introduction Message','Health Department','843-719-4601');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Laboratory','Health Department','843-719-4629');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Medical Records','Health Department','843-719-4602');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Medical Records Fax','Health Department','843-719-4617');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Northwoods Area','Health Department','843-764-1732');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department TB Clinic','Health Department','843-719-4612');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department TB Fax','Health Department','843-719-4778');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department TB Program','Health Department','843-719-4609');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department Vital Statistics','Health Department','843-953-0032');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department WFC Clerk','Health Department','843-719-4621');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department WIC','Health Department','843-719-4670');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Health Department WIC Fax','Health Department','843-719-4781');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Highway Dept. Ladson','Highway Dept','843-572-7854');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Highway Dept. Moncks Corner #1','Highway Dept','843-761-5385');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Highway Dept. State Road Maintenance','Highway Dept','843-761-8481');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Highway Patrol N. Chas','Highway Patrol','843-953-6000');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Home Health','Home Health','843-761-8095');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Home Telephone Repair Service','Home Telephone Repair Service','843-761-9166');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Housing Asst. Charleston','Housing Asst','843-577-0929');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Housing Asst. Moncks Corner','Housing Asst','843-761-8244');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Housing Asst. St. Stephen','Housing Asst','843-825-3679');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Housing Authority','Housing Authority','800-922-5504');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('HUD','Housing Authority','803-765-5592');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Human Resources','Human Resources','843-719-4163');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Human Resources Fax','Human Resources','843-719-4714');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Human Resources MIAP','Human Resources','843-719-4106');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Information Technology','Information Technology','843-719-4004');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Information Technology Courthouse Fax','Information Technology','843-719-4198');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Information Technology Fax','Information Technology','843-719-4024');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Information Technology Help Desk','Information Technology','843-719-4004');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Information Technology Live Oak Fax','Information Technology','843-719-4386');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Internal Revenue Service','Internal Revenue Service','800-829-1040');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Jamestown Town Hall','Jamestown Town Hall','843-257-2233');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Job Line','Job Service','843-719-4232');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Job Service 100 S. Hwy. 52','Job Service','843-761-4400');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Job Service Chas. Line','Job Service Chas. Line','843-722-2082');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Juvenile Justice Moncks Corner','Juvenile Justice Moncks Corner','843-761-8194');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Juveniule Justice Chas. Line','Juveniule Justice Chas. Line','843-723-7196');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Kennedy Center Chas. Line','Kennedy Center','843-577-9181');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Kennedy Center Moncks Corner','Kennedy Center','843-761-8272');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Lawyer Referral Service','Lawyer','800-868-2284');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Legal Aide','Legal Aide','843-720-7044');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Legal Department','Legal','843-719-4011');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Legal Fax Line','Legal','843-719-4306');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Libraries Admin','Libraries','843-719-4224');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Libraries Daniel Island','Libraries','843-471-2952');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Libraries Goose Creek','Libraries','843-572-1376');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Libraries Goose Creek Fax','Libraries','843-572-5680');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Libraries Hanahan','Libraries','843-553-0047');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Libraries Hanahan Fax','Libraries','843-747-5400');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Libraries Moncks Corner','Libraries','843-719-4223');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Libraries Moncks Corner Fax','Libraries','843-719-4226');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Libraries Sangaree','Libraries','843-695-1208');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Libraries St. Stephen','Libraries','843-567-4862');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Libraries St. Stephen Fax','Libraries','843-567-4862');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Lieber Corrections Center','Lieber Corrections Center','843-896-3701');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Macdougall Corrections Center','Macdougall Corrections Center','843-871-0741');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates and Constables Central Summary Court','Magistrate Court','843-719-4050');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates and Constables Goose Creek','Magistrate Court','843-553-7080');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates and Constables Goose Creek Fax','Magistrate Court','843-553-7074');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates and Constables Main Line','Magistrate Court','843-719-4050');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates and Constables Moncks Corner Fax','Magistrate Court','843-719-4528');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates and Constables St. Stephen','Magistrate Court','843-567-7400');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates and Constables St. Stephen Fax','Magistrate Court','843-567-3102');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates and Constables Traffic Court Fax','Magistrate Court','843-719-4534');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates Bond Court','Magistrate Court','843-719-4549');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates Goose Creek','Magistrate Court','843-553-6099');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates Small Claims North (Moncks Corner)','Magistrate Court','843-719-4264');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates Small Claims South (Goose Creek)','Magistrate Court','843-553-6099');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Magistrates Traffic Court','Magistrate Court','843-719-4050');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Maintenance Garage','Maintenance Garage','843-719-4123');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Master In Equity','Master In Equity','843-719-4437');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Master In Equity Fax','Master In Equity','843-719-4397');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Medicaid','Medicaid','843-719-1131');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Mental Health','Mental Health','843-761-8282');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Mental Health Goose Creek','Mental Health','843-569-0070');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Mental Health Toll Free','Mental Health','(888) 202-1381');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Mepkin Abbey','Mepkin Abbey','843-761-8509');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Moncks Corner Police Department','Town of Moncks Corner','843-719-7930');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Moncks Corner Recreation Dept','Town of Moncks Corner','843-719-7900');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Moncks Corner Town Hall','Town of Moncks Corner','843-719-7900');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Moncks Corner Water Dept','Moncks Corner Water Dept','843-719-7965');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Mosquito Abatement','Mosquito Abatement','843-719-4646');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Mosquito Abatement Fax','Mosquito Abatement','843-719-4791');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Mosquito Abatement Workshop','Mosquito Abatement','843-719-4720');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('MUSC Administrator','MUSC','843-719-4774');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('MUSC Nurse Desk','MUSC','843-719-4779');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('MUSC Peds','MUSC','843-719-4774');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('MUSC Physician','MUSC','843-719-4685');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('National Guard Armory','National Guard Armory','843-899-6756');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Old Santee Canal Park','Old Santee Canal Park','843-899-5101');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Old Santee Canal State Park','Old Santee Canal State Park','843-899-5200');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Permitting','Permitting','843-719-4292');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Permitting Fax','Permitting','843-719-4261');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Planning and Zoning','Planning and Zoning','843-719-4095');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Planning and Zoning Fax','Planning and Zoning','843-719-4053');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Poison Control','Poison Control','800-922-1117');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Post & Courier Fax','Post & Courier','843-723-4893');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Post & Courier Fax','Post & Courier','843-937-5503');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Post Office (Moncks Corner)','Post Office','843-761-8455');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Probate Court #1','Probate Court','843-719-4519');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Probate Court #2','Probate Court','843-719-4520');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Probate Court Fax','Probate Court','843-719-4527');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Probation and Parole #1','Probation & Parole','843-761-8395');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Probation and Parole #2','Probation & Parole','843-761-6577');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Procurement','Procurement','843-719-4118');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Procurement Fax','Procurement','843-719-4117');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('PTI Program','PTI Program','843-719-4387');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Public Defender','Public Defender','843-899-2777');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Real Property','Real Property','843-719-4061');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Real Property #2','Real Property','843-719-4062');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Real Property Fax','Real Property','843-719-4271');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Real Property Front Public Room','Real Property','843-719-4101');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Red Cross','Red Cross','843-764-2323');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Register Of Deeds','Register Of Deeds','843-719-4084');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Register Of Deeds Abstractors Ext','Register Of Deeds','843-719-4090');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Register Of Deeds Breakroom','Register Of Deeds','843-719-4910');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Register Of Deeds Fax','Register Of Deeds','843-719-4851');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Register of Deeds Hand-held','Register Of Deeds','843-719-4088');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Register Of Deeds Paralegal Fax','Register Of Deeds','843-719-4139');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Register Of Deeds Paralegals','Register Of Deeds','843-719-4090');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Retail License','Retail License','843-852-3600');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Roads And Bridges','Roads and Bridges','843-719-4129');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Roads And Bridges Fax','Roads and Bridges','843-719-4974');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Roper Berkeley Hospital Moncks Corner','Roper Berkeley','843-899-7700');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Roper Berkeley Medical Offices','Roper Berkeley','843-899-6885');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('RTMA','RTMA','800-966-6631');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('RTMA (Local)','RTMA','843-899-4096');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Safety and Risk Management After Hours','Safety and Risk Management','843-826-7619');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sangaree Special Tax District 2nd #','Sangaree Special Tax District','843-871-9241');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sangaree Special Tax District Main #','Sangaree Special Tax District','843-871-9720');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Santee Canal Historical Society & Museum','Santee Canal Park','843-899-5101');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('SC Center For Equal Justice','SC Center For Equal Justice','843-720-7044');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('SC Center For Equal Justice','SC Center For Equal Justice','(888) 346-5592');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('SC Tax Commission','SC Tax Commission','843-852-3600');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Secretary Of State | Jim Miles','Secretary Of State','803-734-2158');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Section 8 Housing','Housing Authority','803-765-5592');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Senior Citizens Goose Creek','Senior Citizens','843-572-2423');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Senior Citizens Hanahan','Senior Citizens','843-266-0958');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Senior Citizens Moncks Corner','Senior Citizens','843-761-0390');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office','Sheriffs Office','843-719-4465');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office #2','Sheriffs Office','843-719-4392');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Animal Control','Sheriffs Office','843-719-4300');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Civil Process','Sheriffs Office','843-719-4417');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Crime Prevention Volunteers','Sheriffs Office','843-719-4407');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Detective Sergeant','Sheriffs Office','843-719-4415');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Detectives Office','Sheriffs Office','843-719-7009');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Detectives Office Secretary','Sheriffs Office','843-719-7009');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Dispatch','Sheriffs Office','843-719-4505');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Dispatch','Sheriffs Office','843-719-4506');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Drug Hot Line','Sheriffs Office','843-719-4692');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Duty','Sheriffs Office','843-719-4412');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Duty','Sheriffs Office','843-719-4424');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Duty Officer','Sheriffs Office','843-719-4465');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Emergency Training Center','Sheriffs Office','843-719-4350');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Fax','Sheriffs Office','843-719-4427');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Narcotics','Sheriffs Office','843-719-4439');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Narcotics','Sheriffs Office','843-719-4855');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Records','Sheriffs Office','843-719-4418');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Rescue Squard','Sheriffs Office','843-719-4295');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Shift Sergeant','Sheriffs Office','843-719-4706');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office SLED','Sheriffs Office','803-737-9001');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Squad Room','Sheriffs Office','843-719-5127');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office St. Stephen','Sheriffs Office','843-567-3116');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Victims Advocate','Sheriffs Office','843-719-4455');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Warrants','Sheriffs Office','843-719-4420');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Warrants','Sheriffs Office','843-719-4283');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Warrants','Sheriffs Office','843-719-4451');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Warrants','Sheriffs Office','843-719-4696');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Sheriffs Office Warrents','Sheriffs Office','(834) 719-4420');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Social Security Adm. Toll Free','Social Security','(866) 495-0111');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Social Services Charleston','Social Services','843-723-0723');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Social Services Moncks Corner','Social Services','843-761-8044');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Soil And Water Conservation District','Soil And Water Conservation District','843-719-4146');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Solicitors Office','Solicitors Office','843-719-4529');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Solicitors Office Circuit Court','Solicitors Office','843-719-4435');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Solicitors Office Fax','Solicitors Office','843-719-4588');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('South Carolina  Wildlife','SC Wildlife','843-953-9300');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('SPCA','SPCA','843-761-0683');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('SPCA Charleston Line','SPCA','843-747-4849');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('SPCA Goose Creek','SPCA','843-797-0610');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('St. Stephen Town Hall','St. Stephen Town Hall','843-567-3597');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('State News Media Fax','News Media State','803-771-8363');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('State Offices State Road Chas. Line','State Offices State Road Chas','843-723-9541');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Suburban Disposal','Suburban Disposal','843-873-4810');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Summerville Town Hall','Summerville Town Hall','843-871-6000');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Training Center','Training Center','843-719-4350');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Treasurer','Treasurer','843-719-4040');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Trident Regional Charleston','Trident Regional','843-797-7000');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Trident Regional Emergency Room','Trident Regional','843-797-8866');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Trident Regional Moncks Corner','Trident Regional','843-761-5400');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Trident Regional Moncks Corner Medical Center','Trident Regional','843-761-8721');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('United Way','United Way','843-761-6033');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('UPS','Administrative Services','800-742-5877');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Veterans Affairs','Veterans Affairs','843-719-4023');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Veterans Affairs Charleston Line','Veterans Affairs','843-377-8506');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Veterans Affairs Fax Line','Veterans Affairs','843-377-8509');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Vocational Rehab','Vocational Rehab','843-761-6036');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Vocational Rehab','Vocational Rehab','(866) 297-6808');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Voter Registration and Elections','Voter Registration and Elections','843-719-4056');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Voter Registration and Elections Fax','Voter Registration and Elections','843-719-4060');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Waste Industries','Waste Industries','843-875-4900');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water & Sanitation Fax Line Landfill','Water and Sanitation','843-761-6950');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation','Water and Sanitation','843-572-4400');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Admin. Fax Machine','Water and Sanitation','843-719-5309');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Adopt A Hwy','Water and Sanitation','843-761-8817');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Billing Meter Room','Water and Sanitation,','843-719-2641');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Break Room','Water and Sanitation,','843-719-3107');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Conf Rm | Training HR','Water and Sanitation','843-719-2622');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Conf Rm.2nd Floor','Water and Sanitation','843-719-2694');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Conf Rm.Engineering','Water and Sanitation','843-719-2602');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Conf Rm.Executive','Water and Sanitation','843-719-2685');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Control Tower','Water and Sanitation','843-719-2360');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Control Tower (2nd Extension)','Water and Sanitation','843-719-2361');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Copy Room','Water and Sanitation','843-719-2657');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Customer Service','Water and Sanitation','843-719-3010');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation DCIT','Water and Sanitation','843-719-3200');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Dispatch','Water and Sanitation','843-719-3202');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Fax','Water and Sanitation','843-569-5309');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation File Room','Water and Sanitation','843-719-2656');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Finance Fax Line','Water and Sanitation','843-719-4632');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Front Counter','Water and Sanitation','843-719-2668');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Laboratory','Water and Sanitation','843-719-2371');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Landfill Hwy 52','Water and Sanitation','843-761-8817');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Landfill Oakley Road','Water and Sanitation','843-719-2386');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Landfill Shop','Water and Sanitation','843-719-2618');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Litter Complaints Charleston','Water and Sanitation','843-572-4400');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Litter Complaints Moncks Corner','Water and Sanitation','843-761-8817');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Litter Complaints St. Stephen','Water and Sanitation','843-567-2061');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Mechanics Shop/Plant','Water and Sanitation','843-719-2364');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Moncks Corner','Water and Sanitation','843-761-8817');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Operator','Water and Sanitation','843-572-4400');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Printer Room','Water and Sanitation','843-719-2658');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Scalehouse | Subtitle D','Water and Sanitation','843-719-2614');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Scalehouse | Subtitle D (2nd Extension)','Water and Sanitation','843-719-2615');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Shipping & Receiving','Water and Sanitation','843-719-2344');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Solid Waste Center Bonneau','Water and Sanitation','843-825-4111');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Solid Waste Center Cordesville','Water and Sanitation','843-336-5005');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Solid Waste Center Cross','Water and Sanitation','843-753-7090');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Solid Waste Center Huger','Water and Sanitation','843-336-3111');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Solid Waste Center Jamestown','Water and Sanitation','843-257-2118');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Solid Waste Center Pineville','Water and Sanitation','843-567-2261');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Solid Waste Center Ridgeville','Water and Sanitation','843-688-5750');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Solid Waste Center Shulerville','Water and Sanitation','843-257-2127');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Solid Waste Moncks Corner','Water and Sanitation','843-761-1782');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation St. Stephen','Water and Sanitation','843-567-2061');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Water and Sanitation Training Room','Water and Sanitation','843-719-2622');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Wildlife Dept.','Department of Natural Resources','843-825-3387');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Wildlife Dept. Charleston','Department of Natural Resources','843-762-5000');
INSERT INTO data_phone_numbers (sPhoneName, sPhoneOrg, sPhoneNumber) values ('Wildlife Dept. Moncks Corner','Department of Natural Resources','843-761-8829');
